# Generated by Django 3.2.3 on 2021-07-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210702_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='pub_date',
            new_name='date',
        ),
    ]
